name: Automerge
on:
  workflow_dispatch:
  schedule:
    - cron: '17 2,5,8,11 * * *'

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.AUTOMERGE_ACCESS_TOKEN }}
